import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header/Header";

const dmSuns = DM_Sans({
    variable: "--dm-suns",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${dmSuns.variable} antialiased`}>
                <Header />
                {children}
            </body>
        </html>
    );
}
